### PR TITLE
Added possibility to exclude IPs

### PR DESCRIPTION
**Pull request by tokarev-artem**

### CODE REVIEW

**Comment by vdeville** [comment]
Hello,
Thanks for your contribution ! Can you replace the string with an bash array ?
Thanks

**Comment by atokarevlnv** [comment]
Hello,
I also thought about this, but it doesn't make any sense
in one case if will be like 

`echo 8.8.8.8 38630 22 | awk '{print $1}' | grep -v 8.8.8.8 4.4.4.4 6.6.6.6)`

In second case it will compare SSH_CLIENT variable with array of ignored IPs, first way is easier I think

What do you think?

**Comment by vdeville** [comment]
Hello,

Okay, let's merge ! 
I will make a little refactoring after.

Thanks

**Comment by vdeville** [comment]
Whats is your system ? On ubuntu, the script doesn't work
Thanks

**Comment by tokarev-artem** [comment]
Tested on Centos,
could you explain please, what is the issue ?

**Comment by vdeville** [comment]
Hello @RealArtemiy 
Here a example on bash ubuntu:
```bash
➜  ~ EXCLUDE_IPS="12.34.56.78 87.65.54.32 8.8.8.8"
➜  ~ echo 8.8.6.8 38630 22 | awk '{print $1}' | grep -v $EXCLUDE_IPS
8.8.6.8
➜  ~ echo 8.8.8.8 38630 22 | awk '{print $1}' | grep -v $EXCLUDE_IPS
8.8.8.8
➜  ~ 
```

**Pull request merged**
